### ISSUE TITLE
invalid path

### ISSUE THREAD

**Issue by marix88** [muneeb-mbytes/verilogHDL#1]
Could you please modify this path? This is what I see in the console when I try to clone your wiki:

error: invalid path 'User-Defined-Primitives(UDP):.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.

**Comment by vineethkumarv** [comment]
Hi marix88, 
Did you try the same command for wiki cloning,
git clone https://github.com/muneeb-mbytes/verilogHDL.wiki.git

For repo cloning,
SSH
git clone git@github.com:muneeb-mbytes/verilogHDL.git
HTTP 
git clone https://github.com/muneeb-mbytes/verilogHDL.git

And which OS you are using?

**Comment by marix88** [comment]
I'm using Windows 11. I get the same error when I try git clone https://github.com/muneeb-mbytes/verilogHDL.wiki.git
The : at the end of this URL might be the problem. 
https://github.com/muneeb-mbytes/verilogHDL/wiki/User-Defined-Primitives(UDP):

**Comment by nancydimri** [comment]
Hi, 
I tried to clone this repo and successfully cloned it. 
As I understand, this is something setup issue.
Have you changed your git configuration(user id or email)
Can you check your git configuration, use the command - **git config --list** .

Suppose you have changed your configuration. In your terminal, run the command **git commit --amend -no-edit**. 
Then try to clone. Maybe it will be helpful.

**Comment by marix88** [comment]
Nothing worked. I don't have any issues with cloning other wikis, it's just the link with : that prevents me from cloning your wiki. After the error I also got this: 

> warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
> and retry with 'git restore --source=HEAD :/'

I retried using that command but I got this in the console after a new failed attempt:

> fatal: unable to update url base from redirection:
>   asked for: https://github.com/muneeb-mbytes/verilogHDL/wiki/info/refs?service=git-upload-pack
>    redirect: https://github.com/muneeb-mbytes/verilogHDL/wiki/

Is there a way to clone your wiki by excluding that page with the bad link?

**Comment by gopalvamsi09** [comment]
Hi Marix88

In windows environment the file name should not consists of  some special characters and some reserved names as shown in below image. That's why you are getting error. Try to clone in Linux

![image](https://github.com/muneeb-mbytes/verilogHDL/assets/113415528/1a4fc2eb-f4f5-445f-8d95-dfc8094d8e4c)
I am suggesting you to work in the Linux environment as Linux is widely using in the industry.

**Comment by muneebullashariff** [comment]
> Nothing worked. I don't have any issues with cloning other wikis, it's just the link with : that prevents me from cloning your wiki. After the error I also got this:
> 
> > warning: Clone succeeded, but checkout failed.
> > You can inspect what was checked out with 'git status'
> > and retry with 'git restore --source=HEAD :/'
> 
> I retried using that command but I got this in the console after a new failed attempt:
> 
> > fatal: unable to update url base from redirection:
> > asked for: https://github.com/muneeb-mbytes/verilogHDL/wiki/info/refs?service=git-upload-pack
> > redirect: https://github.com/muneeb-mbytes/verilogHDL/wiki/
> 
> Is there a way to clone your wiki by excluding that page with the bad link?

Has this issue been resolved?

**Comment by marix88** [comment]
Yes, I just did it on Linux and it worked without problems.
